# version: '3.8'

# services:
#   backend:
#     container_name: pipe_backend
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/backend
#     environment:
#       - FLASK_ENV=development

#   frontend:
#     container_name: pipe_frontend
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "3000:80"  # Changed from 80 to match typical React/Vue ports
#     # volumes:
#     #   - ./frontend:/app  # Fixed incomplete volume declaratio
#     volumes:
#       - ./frontend:/usr/share/nginx/html  # Live-reload files (optional)n



version: '3.8'

services:
  backend:
    container_name: pipe_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  frontend:
    container_name: pipe_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
