version: '3.8'

services:
  backend:
    container_name: pipe_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    container_name: pipe_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Changed from 80 to match typical React/Vue ports
    volumes:
      - ./frontend:/app  # Fixed incomplete volume declaration